export const TestServiceDefinition = {
  serviceName: 'TestService',
  methods: {
    list: { asyncModel: 'requestResponse' as 'requestResponse' },
  },
};

export const fixture = {
  time: {},
  user: { email: 'vi****an@jivygroup.com' },
  uuid: '5634bf89-b271-40c5-be0c-794e6d5c6429',
  qualifier: 'InstrumentService/list$',
  result: {
    type: 'snapshot',
    data: {
      '0': {
        id: '1',
        isHalted: false,
        symbol: 'IVV',
        quoteCurrency: 'USD',
        instrumentDescription: 'iShares Core S&P 500 ETF',
        calendarId: '59684565',
        pricePrecision: 2,
        quantityPrecision: 6,
        minQuantity: 1,
        maxQuantity: 10000,
        quantityIncrement: 0.000001,
        status: 'Active',
        marketStatus: 'opened',
      },
      '1': {
        id: '2',
        isHalted: false,
        symbol: 'zAMZ',
        quoteCurrency: 'USD',
        instrumentDescription: 'Test',
        calendarId: '59684565',
        pricePrecision: 8,
        quantityPrecision: 8,
        minQuantity: 1,
        maxQuantity: 99999999,
        status: 'Active',
        marketStatus: 'opened',
      },
      '2': {
        id: '3',
        isHalted: false,
        symbol: 'Demo1',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing instruments',
        calendarId: '59684565',
        pricePrecision: 6,
        quantityPrecision: 6,
        minQuantity: 1,
        maxQuantity: 100000000,
        status: 'Active',
        marketStatus: 'opened',
      },
      '3': {
        id: '4',
        isHalted: false,
        symbol: 'test',
        quoteCurrency: 'USD',
        instrumentDescription: 'test instrument',
        calendarId: '361125114',
        pricePrecision: 6,
        quantityPrecision: 2,
        minQuantity: 1,
        maxQuantity: 100000,
        status: 'Active',
        marketStatus: 'opened',
      },
      '4': {
        id: '5',
        isHalted: false,
        symbol: 'Test2',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing',
        calendarId: '361125114',
        pricePrecision: 6,
        quantityPrecision: 6,
        minQuantity: 1,
        maxQuantity: 100000000,
        status: 'Active',
        marketStatus: 'opened',
      },
      '5': {
        id: '6',
        isHalted: false,
        symbol: 'Test3',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing',
        calendarId: '361125114',
        pricePrecision: 6,
        quantityPrecision: 6,
        minQuantity: 1,
        maxQuantity: 10000000,
        status: 'Active',
        marketStatus: 'opened',
        auctions: {
          '0': {
            days: {
              '0': 'Sunday',
              '1': 'Monday',
              '2': 'Tuesday',
              '3': 'Wednesday',
              '4': 'Thursday',
              '5': 'Friday',
              '6': 'Saturday',
            },
            startTimes: { '0': '07:57' },
            allowedTimeInForces: { '0': 'GTC', '1': 'GTD', '2': 'GAA' },
            eventsMode: { '0': 'LIT', '1': 'Indicative Price' },
            duration: { number: 4, measurement: 'm' },
            randomEndTime: { number: 0, measurement: 'm' },
            crossingPause: { number: 0, measurement: 'm' },
            indicativePriceFrequency: { number: 10, measurement: 's' },
            auctionType: 'Many To Many',
            matchingAlgorithm: 'Price & Time',
          },
        },
      },
      '6': {
        id: '7',
        isHalted: false,
        symbol: 'Test4',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing instrument',
        calendarId: '346004012',
        pricePrecision: 6,
        quantityPrecision: 6,
        minQuantity: 1,
        maxQuantity: 100000000,
        status: 'Active',
        auctions: null,
        marketStatus: 'closed',
      },
      '7': {
        id: '8',
        isHalted: false,
        symbol: 'Test5',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing',
        calendarId: '59684565',
        pricePrecision: 3,
        quantityPrecision: 6,
        minQuantity: 1,
        maxQuantity: 10000000,
        status: 'Active',
        auctions: null,
        marketStatus: 'opened',
      },
      '8': {
        id: '9',
        isHalted: false,
        symbol: 'AUC1',
        quoteCurrency: 'USD',
        instrumentDescription: 'Test',
        calendarId: '59684565',
        pricePrecision: 6,
        quantityPrecision: 4,
        minQuantity: 0.0001,
        maxQuantity: 10000000,
        status: 'Active',
        marketStatus: 'opened',
      },
      '9': {
        id: '10',
        isHalted: false,
        symbol: 'Monitor',
        quoteCurrency: 'UAS',
        instrumentDescription: 'Monitor Ins',
        calendarId: '59684565',
        pricePrecision: 8,
        quantityPrecision: 8,
        minQuantity: 1e-7,
        maxQuantity: 100000000,
        status: 'Active',
        auctions: {},
        marketStatus: 'opened',
      },
      '10': {
        id: '11',
        isHalted: false,
        symbol: 'BBC',
        quoteCurrency: 'USD',
        instrumentDescription: 'test',
        calendarId: '509603053',
        pricePrecision: 7,
        quantityPrecision: 1,
        minQuantity: 1,
        maxQuantity: 10000000,
        status: 'Active',
        marketStatus: 'opened',
        quantityIncrement: 0.5,
        auctions: {
          '0': {
            days: { '0': 'Sunday', '1': 'Monday', '2': 'Tuesday', '3': 'Wednesday', '4': 'Thursday' },
            startTimes: { '0': '08:38' },
            allowedTimeInForces: { '0': 'GTC', '1': 'GTD', '2': 'GAA' },
            eventsMode: { '0': 'Indicative Price', '1': 'LIT' },
            duration: { number: 2, measurement: 'm' },
            randomEndTime: { number: 0, measurement: 'm' },
            crossingPause: { number: 1, measurement: 'm' },
            indicativePriceFrequency: { number: 10, measurement: 's' },
            auctionType: 'Many To Many',
            matchingAlgorithm: 'Equilibrium Price',
          },
        },
        tickSizeGroupId: '1497704209',
      },
      '11': {
        id: '12',
        isHalted: false,
        symbol: 'aTest',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing',
        calendarId: '509603053',
        pricePrecision: 4,
        quantityPrecision: 10,
        minQuantity: 1,
        maxQuantity: 922337203,
        status: 'Active',
        marketStatus: 'opened',
        auctions: {
          '0': {
            days: { '0': 'Sunday', '1': 'Monday', '2': 'Tuesday', '3': 'Wednesday', '4': 'Thursday' },
            startTimes: { '0': '12:51' },
            allowedTimeInForces: { '0': 'GTC', '1': 'GTD', '2': 'GAA' },
            eventsMode: { '0': 'LIT', '1': 'Indicative Price' },
            duration: { number: 5, measurement: 'm' },
            randomEndTime: { number: 0, measurement: 'm' },
            crossingPause: { number: 0, measurement: 'm' },
            indicativePriceFrequency: { number: 10, measurement: 's' },
            auctionType: 'Many To Many',
            matchingAlgorithm: 'Price & Time',
          },
        },
      },
      '12': {
        id: '13',
        isHalted: false,
        symbol: 'AMZ',
        quoteCurrency: 'USD',
        instrumentDescription: 'instest',
        calendarId: '509603053',
        pricePrecision: 4,
        quantityPrecision: 3,
        minQuantity: 185,
        maxQuantity: 10048,
        status: 'Disabled',
        marketStatus: 'opened',
      },
      '13': {
        id: '14',
        isHalted: false,
        symbol: 'Gold',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing instrument',
        calendarId: '59684565',
        pricePrecision: 9,
        quantityPrecision: 10,
        minQuantity: 1,
        maxQuantity: 10000,
        status: 'Active',
        marketStatus: 'opened',
      },
      '14': {
        id: '15',
        isHalted: false,
        symbol: 'APL',
        quoteCurrency: 'USD',
        instrumentDescription: 'Apple',
        calendarId: '59684565',
        pricePrecision: 5,
        quantityPrecision: 0,
        minQuantity: 147,
        maxQuantity: 78004,
        status: 'Active',
        marketStatus: 'opened',
      },
      '15': {
        id: '16',
        isHalted: false,
        symbol: 'aBBC',
        quoteCurrency: 'USD',
        instrumentDescription: 'test',
        calendarId: '509603053',
        pricePrecision: 6,
        quantityPrecision: 6,
        minQuantity: 77,
        maxQuantity: 10254,
        status: 'Active',
        marketStatus: 'opened',
        tickSizeGroupId: '1009095816',
      },
      '16': {
        id: '17',
        isHalted: false,
        symbol: 'DUD',
        quoteCurrency: 'USD',
        instrumentDescription: 'fff',
        calendarId: '59684565',
        pricePrecision: 6,
        quantityPrecision: 6,
        minQuantity: 0.000001,
        maxQuantity: 100004,
        status: 'Active',
        marketStatus: 'opened',
      },
      '17': {
        id: '18',
        isHalted: false,
        symbol: 'BBC1',
        quoteCurrency: 'USD',
        instrumentDescription: 'test',
        calendarId: '59684565',
        pricePrecision: 3,
        quantityPrecision: 6,
        minQuantity: 1,
        maxQuantity: 100000000,
        tickSizeGroupId: null,
        status: 'Active',
        auctions: null,
        marketStatus: 'opened',
      },
      '18': {
        id: '19',
        isHalted: false,
        symbol: 'DUD1',
        quoteCurrency: 'UDD',
        instrumentDescription: 'khkh',
        calendarId: '59684565',
        pricePrecision: 6,
        quantityPrecision: 6,
        minQuantity: 0.00001,
        maxQuantity: 10000000,
        tickSizeGroupId: null,
        status: 'Active',
        auctions: null,
        marketStatus: 'opened',
      },
      '19': {
        id: '20',
        isHalted: false,
        symbol: 'ihatekafka',
        quoteCurrency: 'usd',
        instrumentDescription: 'test',
        calendarId: '59684565',
        pricePrecision: 8,
        quantityPrecision: 8,
        minQuantity: 5,
        maxQuantity: 7777,
        tickSizeGroupId: null,
        status: 'Active',
        auctions: null,
        marketStatus: 'opened',
      },
      '20': {
        id: '21',
        isHalted: false,
        symbol: 'Test1',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing',
        calendarId: '59684565',
        pricePrecision: 2,
        quantityPrecision: 2,
        minQuantity: 1,
        maxQuantity: 99999999,
        tickSizeGroupId: null,
        status: 'Active',
        auctions: null,
        marketStatus: 'opened',
      },
      '21': {
        id: '22',
        isHalted: false,
        symbol: 'test12',
        quoteCurrency: 'USD',
        instrumentDescription: 'test',
        calendarId: '59684565',
        pricePrecision: 1,
        quantityPrecision: 3,
        minQuantity: 1,
        maxQuantity: 10000000,
        tickSizeGroupId: null,
        status: 'Active',
        auctions: null,
        marketStatus: 'opened',
      },
      '22': {
        id: '23',
        isHalted: false,
        symbol: 'AAA',
        quoteCurrency: 'USD',
        instrumentDescription: 'test',
        calendarId: '59684565',
        pricePrecision: 3,
        quantityPrecision: 6,
        minQuantity: 15,
        maxQuantity: 100000000,
        status: 'Active',
        marketStatus: 'opened',
      },
      '23': {
        id: '24',
        isHalted: false,
        symbol: 'aSymbol',
        quoteCurrency: 'USD',
        instrumentDescription: 'testing instrument',
        calendarId: '59684565',
        pricePrecision: 10,
        quantityPrecision: 10,
        minQuantity: 0.001,
        maxQuantity: 100000000,
        status: 'Active',
        auctions: {
          '0': {
            days: { '0': 'Saturday', '1': 'Sunday' },
            startTimes: { '0': '23:09' },
            allowedTimeInForces: { '0': 'GTC', '1': 'GTD', '2': 'GAA' },
            eventsMode: { '0': 'LIT', '1': 'Indicative Price' },
            duration: { number: 3, measurement: 'm' },
            randomEndTime: { number: 30, measurement: 's' },
            crossingPause: { number: 30, measurement: 's' },
            indicativePriceFrequency: { number: 10, measurement: 's' },
            auctionType: 'Many To Many',
            matchingAlgorithm: 'Equilibrium Price',
          },
        },
        marketStatus: 'opened',
      },
      '24': {
        id: '25',
        isHalted: false,
        symbol: 'Symbol1',
        quoteCurrency: 'USD',
        instrumentDescription: 'test',
        calendarId: '509603053',
        pricePrecision: 4,
        quantityPrecision: 4,
        minQuantity: 1,
        maxQuantity: 100000000,
        status: 'Active',
        auctions: {
          '0': {
            days: { '0': 'Sunday', '1': 'Monday', '2': 'Tuesday', '3': 'Wednesday', '4': 'Thursday' },
            startTimes: { '0': '13:38' },
            allowedTimeInForces: { '0': 'GTC', '1': 'GTD', '2': 'GAA' },
            eventsMode: { '0': 'LIT', '1': 'Indicative Price' },
            duration: { number: 2, measurement: 'm' },
            randomEndTime: { number: 0, measurement: 'm' },
            crossingPause: { number: 0, measurement: 'm' },
            indicativePriceFrequency: { number: 30, measurement: 's' },
            auctionType: 'Many To Many',
            matchingAlgorithm: 'Equilibrium Price',
          },
        },
        marketStatus: 'opened',
      },
      '25': {
        id: '26',
        isHalted: false,
        symbol: 'AAA1',
        quoteCurrency: 'USD',
        instrumentDescription: 'test',
        calendarId: '59684565',
        pricePrecision: 3,
        quantityPrecision: 8,
        minQuantity: 1,
        maxQuantity: 100000000,
        status: 'Active',
        marketStatus: 'opened',
      },
    },
  },
};

export class TestService {
  constructor() {}

  public async list() {
    return fixture;
  }
}
